### ISSUE TITLE
Incorrect documentation to add the card

### ISSUE THREAD

**Issue by manju-rn** [custom-cards/entity-attributes-card#11]
There is incorrect documentation when the card is installed.  It shows below
``` 
- url: /community_plugin/entity-attributes-card/entity-attributes-card.js
  type:
```
This is missing the 2 important points and detailed instruction for any first time user. I would suggest adding the below:
1. Go to Raw Config Editor in HA UI.   Overview -> Click on 3 dots -> Configure UI -> Click on 3 Dots again -> Raw Config Editor
2.  Add the below configuration.  Please note that the resources should be in the same indentation level as that of views: and title:
```
resources:
  - url: /community_plugin/entity-attributes-card/entity-attributes-card.js
    type: module
```
Typically it should be added between Title and View, like below
```
title: Home
resources:
  - url: /community_plugin/entity-attributes-card/entity-attributes-card.js
    type: module
views:
  - badges:
```
