### ISSUE TITLE
0.106 breaks it

### ISSUE THREAD

**Issue by IanAdd** [custom-cards/entity-attributes-card#13]
Further to previous warning by thomasloven. It now appears broken in 0.106.2
```
              - entities:
                  - entity: media_player.lounge
                  - filter:
                      include:
                        - media_player.lounge.media_album_name
                        - media_player.lounge.media_title
                        - media_player.lounge.media_artist
                        - media_player.lounge.source
                        - media_player.lounge.sonos_group
                    type: 'custom:entity-attributes-card'
                show_header_toggle: false
                title: Lounge
                type: entities
```
gives....

![HA_e_a_card](https://user-images.githubusercontent.com/10492213/75621175-9396e680-5be5-11ea-9737-e0989e6f181d.jpg)
