### ISSUE TITLE
Exclude filter not working with sensor.plex... 

### ISSUE THREAD

**Issue by BackedUpBooty** [custom-cards/entity-attributes-card#21]
I wanted to set up a card which showed me current plex users (rather than the inbuilt option of seeing how many were on the server at any one time) and I found a link which laid out the following:

``` 
      - type: custom:entity-attributes-card
        title: Plex Current Users
        heading_name: Name
        heading_state: Currently Watching
        filter:
          include:
            - key: sensor.plex.*
          exclude:
            - key: sensor.plex.unit_of_measurement
            - key: sensor.plex.friendly_name
            - key: sensor.plex.body
 ```
However I get the same information regardless of whether I specify excluded sensors or not as follows:
![image](https://user-images.githubusercontent.com/53868636/123083261-dcb61e00-d45a-11eb-8662-834f663c1402.png)

I can't find any reason why this wouldn't be working, and I can't find any other similar issues so submitting a new one here.
