### ISSUE TITLE
[Feature request] Add formatting option for keys of type date/time

### ISSUE THREAD

**Issue by bcutter** [custom-cards/entity-attributes-card#22]
**Problem:**
Currently keys are "just" shown plain as they are in the database.

This leads to very uncomfortable reading as well as wrong values (because the timezone is not considered!) when it comes to dates/times.

**Example:**
```
type: conditional
conditions:
  - entity: sensor.dwd_wetterwarnung_current_warning_level
    state_not: '0'
card:
  type: custom:entity-attributes-card
  title: ❗ Wetterwarnung ❗
  heading_name: ' '
  heading_state: 'Aktuelle Warnung(en):'
  filter:
    include:
      - key: sensor.dwd_wetterwarnung_current_warning_level.warning_1_name
        name: ▶
      - key: sensor.dwd_wetterwarnung_current_warning_level.warning_1_headline
        name: ' '
      - key: sensor.dwd_wetterwarnung_current_warning_level.warning_1_description
        name: ' '
      - key: sensor.dwd_wetterwarnung_current_warning_level.warning_1_start
        name: 'Von:'
      - key: sensor.dwd_wetterwarnung_current_warning_level.warning_1_end
        name: 'Bis:'
      - key: sensor.dwd_wetterwarnung_current_warning_level.warning_2_name
        name: ▶
      - key: sensor.dwd_wetterwarnung_current_warning_level.warning_2_headline
        name: ' '
      - key: sensor.dwd_wetterwarnung_current_warning_level.warning_2_description
        name: ' '
      - key: sensor.dwd_wetterwarnung_current_warning_level.warning_2_start
        name: 'Von:'
      - key: sensor.dwd_wetterwarnung_current_warning_level.warning_2_end
        name: 'Bis:'
```

Very hard to read:
![grafik](https://user-images.githubusercontent.com/13799156/143686589-05740271-2f7a-4927-b0c5-cd0bdfa588b6.png)

**Proposal:**
Add out of the box formatting option for keys to handle the way date/time keys are shown.

**Implementation example:**
See https://github.com/benct/lovelace-multiple-entity-row#formatting which is able to create perfectly readable output
![grafik](https://user-images.githubusercontent.com/13799156/143686718-3866bf9c-0851-47d5-a1be-f1333e257539.png)
