### ISSUE TITLE
Cannot read property 'setConfig' of undefined

### ISSUE THREAD

**Issue by AngelofromTurin** [custom-cards/entity-attributes-card#5]
hi, 
i tried to use thise card, but i have thise messagge in the ui editor....
i tried with type js and module in the main config lovelace...
what can i do ?

**Comment by aeckard87** [comment]
Hey @AngelofromTurin, just found this gem myself! I realized after playing around that you have to put the attribute name next to the entity in the key field:

Not sure if this is where your issue was, but hope it helps someone :)

_key: binary_sensor.hallway_sensor_motion.**battery_level**_

```yaml
  - type: custom:entity-attributes-card
    title: Attributes
    heading_name: Entity
    heading_state: Battery Level
    filter:
      include:
        - key: binary_sensor.hallway_sensor_motion.battery_level
          name: Hallway Sensor
```


![Annotation 2020-01-02 012500](https://user-images.githubusercontent.com/7349698/71654290-e98f0100-2cfe-11ea-8a71-4a69ad7f7567.png)
